Implement functionality to export player summary excel. Also separated dev/prod db and backend (#11)
* Added support for scoring game excel exporting

* Added functionality for player stats summary excel export

* frontend changes

* BUGFIX: Merge conflict resolution left ExcelExporter.jsx with some duplicate code. Cleaned

* Small bugfixes removing duplicated code

diff --git a/.github/workflows/keep-alive.yml b/.github/workflows/keep-alive.yml
--- a/.github/workflows/keep-alive.yml
+++ b/.github/workflows/keep-alive.yml
@@ -3,12 +3,11 @@ name: Keep Render App Alive
 on:
   schedule:
     - cron: "*/5 * * * *"
-  workflow_dispatch:        # enables manual trigger button
-
+  workflow_dispatch: # enables manual trigger button
 
 jobs:
   ping:
     runs-on: ubuntu-latest
     steps:
       - name: Ping Render App
-        run: curl -fsSL https://scoring-app-3-dev.onrender.com/ || echo "Failed to ping Render app"
+        run: curl -fsSL https://prod-scoring-app-3-prod.onrender.com/ || echo "Failed to ping Render app"
